name: instagram_login_app
description: Instagram Mobile API Login Flutter Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP istekleri için
  http: ^1.1.0
  dio: ^5.3.2
  
  # State management
  provider: ^6.0.5
  
  # Local storage
  shared_preferences: ^2.2.1
  
  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0
  
  # Animations
  animate_do: ^3.1.2
  animated_text_kit: ^4.2.2
  
  # Crypto
  crypto: ^3.0.3
  encrypt: ^5.0.3
  
  # UUID generation
  uuid: ^4.2.1
  
  # Toast messages
  fluttertoast: ^8.2.4
  
  # Gradient
  simple_gradient_text: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets için (eğer logo vs eklemek isterseniz)
  # assets:
  #   - assets/images/
  #   - assets/icons/